apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-view-resourses
  namespace: default
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-resource-viewer
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engineer-edit-resources
  namespace: default
subjects:
- kind: User
  name: engineer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-resource-editor
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-admin-secrets
  namespace: default
subjects:
- kind: User
  name: devops
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cluster-secrets-admin
  apiGroup: rbac.authorization.k8s.io
